### ISSUE TITLE
ClassNotFoundException: Didn't find class "com.everyplay.Everyplay.R$layout

### ISSUE THREAD

**Issue by alaa-eddine** [Everyplay/everyplay-android-sdk#12]
Hello,

I'm trying to integrate everyplay SDK to a custom android project (not unity), but I'm getting the error above.

the error occures when I call  : Everyplay.showEveryplay();

and it cause application crash.

I copied the content of /res directory from everyplay repository to my project /res without success.

any idea of how to fix it ?

Many thanks

```
6544:I/ActivityManager(  776): START u0 {flg=0x10000 cmp=com.eztest.everyplayapp/com.everyplay.Everyplay.view.EveryplaySocialActivity (has extras)} from uid 10429 on display 0
6545:V/WindowManager(  776): addAppToken: AppWindowToken{87685d9 token=Token{17e9a820 ActivityRecord{281c5b23 u0 com.eztest.everyplayapp/com.everyplay.Everyplay.view.EveryplaySocialActivity t10238}}} to stack=1 task=10238 at 1
6559:D/PTServicesBridge(32411): onEveryplayShown
6574:E/AndroidRuntime(32411): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/everyplay/Everyplay/R$layout;
6575:E/AndroidRuntime(32411):   at com.everyplay.Everyplay.view.ag.<init>(Unknown Source)
6576:E/AndroidRuntime(32411):   at com.everyplay.Everyplay.view.bi.m(Unknown Source)
6577:E/AndroidRuntime(32411):   at com.everyplay.Everyplay.view.bi.<init>(Unknown Source)
6578:E/AndroidRuntime(32411):   at com.everyplay.Everyplay.view.f.b(Unknown Source)
6579:E/AndroidRuntime(32411):   at com.everyplay.Everyplay.view.EveryplaySocialActivity.onCreate(Unknown Source)
6593:E/AndroidRuntime(32411): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.everyplay.Everyplay.R$layout" on path: DexPathList[[zip file "/data/app/com.eztest.everyplayapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.eztest.everyplayapp-1/lib/arm, /vendor/lib, /system/lib]]

```

**Comment by paugit** [comment]
Closing this really old unsolved issue. Please re-open the issue if it is still valid with the latest Everyplay (2150-1570).
